# docker-compose.yml
name: resume-pdf-export
services:
  resume-pdf-export:
    build: .
    container_name: resume-pdf-export
    hostname: resume-pdf-export
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
